// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://topikrqamdglxakppbyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcGlrcnFhbWRnbHhha3BwYnlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDA5ODEsImV4cCI6MjA1NzE3Njk4MX0.rr-cXk_vlf6HKtCkoUzdbuol1tSusvOq2nMyXgYWSCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);